apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  code-quality:
    outputs:
      output1: ${{ steps.setvalues.outputs.envvalue }}
      output2: ${{ steps.setvalues.outputs.tagvalue }}
      test-run: ${{ steps.setvalues.outputs.testrun }}
    steps:
      
      - uses: cloudbees-io/checkout@v1
      - name: Say hello
        id: setvalues
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo "QA" > $CLOUDBEES_OUTPUTS/envvalue
          echo "Login" > $CLOUDBEES_OUTPUTS/tagvalue
          echo "true" > $CLOUDBEES_OUTPUTS/testrun
        
    
  test:
    needs: ['code-quality']
    if: ${{needs.code-quality.outputs.test-run == 'true' }}
    steps:
      - uses: cloudbees-io/checkout@v1
    
