apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:

jobs:
  code-quality:
    outputs:
      output1: ${{ steps.setvalues.outputs.envvalue }}
      output2: ${{ steps.setvalues.outputs.tagvalue }}
      testrun: ${{ steps.setvalues.outputs.testrun }}
    steps:
      
      - uses: cloudbees-io/checkout@v1
      - name: Say hello
        id: setvalues
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
          echo "QA" > $CLOUDBEES_OUTPUTS/envvalue
          echo "Login" > $CLOUDBEES_OUTPUTS/tagvalue
          echo "false" > $CLOUDBEES_OUTPUTS/testrun
        
    
  test:
    needs: ['code-quality']
    if: ${{needs.code-quality.outputs.testrun == 'true' }}
    steps:
      - uses: cloudbees-io/checkout@v1
      - name: Echo values
        id: setvalues
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo ${{ needs.code-quality.outputs.testrun  }}
          echo ${{ needs.code-quality.outputs.output1  }}
          echo ${{ needs.code-quality.outputs.output2  }}
    
