apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: RobKLetsGo
on:
  workflow_dispatch:
jobs:
  build:
    environment: Approval
    steps:
      - name: Say hello
        run: |
          echo "hello world"
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
